"""add icon to collections + sync email unique index

Revision ID: 20ca8554a5fa
Revises: 1fa8d30e18d4
Create Date: 2026-05-13 02:24:04.386299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ca8554a5fa'
down_revision: Union[str, Sequence[str], None] = '1fa8d30e18d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('icon', sa.String(length=10), nullable=True))
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('collections', 'icon')
    # ### end Alembic commands ###
