"""naming convention, indexes, source_type check

Revision ID: 745174bb88f4
Revises: 8ea96bec4c37
Create Date: 2026-05-28 17:29:12.748163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '745174bb88f4'
down_revision: Union[str, Sequence[str], None] = '8ea96bec4c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collections', 'icon',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.drop_index(op.f('uq_collections_user_id_parent_id_name'), table_name='collections', postgresql_nulls_not_distinct=True)
    op.create_index(op.f('ix_collections_user_id_parent_id'), 'collections', ['user_id', 'parent_id'], unique=False)
    op.create_index(op.f('ix_collections_user_id_parent_id_name'), 'collections', ['user_id', 'parent_id', 'name'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_index(op.f('ix_material_tags_tag_id'), 'material_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_materials_collection_id_created_at'), 'materials', ['collection_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_collection_id_created_at'), table_name='materials')
    op.drop_index(op.f('ix_material_tags_tag_id'), table_name='material_tags')
    op.drop_index(op.f('ix_collections_user_id_parent_id_name'), table_name='collections', postgresql_nulls_not_distinct=True)
    op.drop_index(op.f('ix_collections_user_id_parent_id'), table_name='collections')
    op.create_index(op.f('uq_collections_user_id_parent_id_name'), 'collections', ['user_id', 'parent_id', 'name'], unique=True, postgresql_nulls_not_distinct=True)
    op.alter_column('collections', 'icon',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
