"""add last_login_at to auth_accounts

Revision ID: 8ea96bec4c37
Revises: a45279897631
Create Date: 2026-05-28 02:23:23.294305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea96bec4c37'
down_revision: Union[str, Sequence[str], None] = 'a45279897631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_accounts', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_accounts', 'last_login_at')
    # ### end Alembic commands ###
