"""add updated_at and email lowercase check to users

Revision ID: a45279897631
Revises: dc5ab4d5a451
Create Date: 2026-05-28 01:39:08.850614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45279897631'
down_revision: Union[str, Sequence[str], None] = 'dc5ab4d5a451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',
                  sa.Column(
                      'updated_at',
                      sa.DateTime(timezone=True),
                      server_default=sa.text('now()'),
                      nullable=False,
                      ),
    )

    op.execute("UPDATE users SET email = LOWER(email) WHERE email <> LOWER(email)")

    op.create_check_constraint(
        'email_lowercase',
        'users',
        'email = LOWER(email)',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_email_lowercase', 'users', type_='check')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
