"""add relationships

Revision ID: 30c860acd59c
Revises: fa73e1b15eaa
Create Date: 2026-03-16 16:02:23.423132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30c860acd59c'
down_revision: Union[str, Sequence[str], None] = 'fa73e1b15eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.drop_constraint(op.f('material_tags_tag_id_fkey'), 'material_tags', type_='foreignkey')
    op.drop_constraint(op.f('material_tags_material_id_fkey'), 'material_tags', type_='foreignkey')
    op.create_foreign_key(None, 'material_tags', 'materials', ['material_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'material_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.alter_column('materials', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_materials_collection_id'), 'materials', ['collection_id'], unique=False)
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_index(op.f('ix_materials_collection_id'), table_name='materials')
    op.alter_column('materials', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'material_tags', type_='foreignkey')
    op.drop_constraint(None, 'material_tags', type_='foreignkey')
    op.create_foreign_key(op.f('material_tags_material_id_fkey'), 'material_tags', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(op.f('material_tags_tag_id_fkey'), 'material_tags', 'tags', ['tag_id'], ['id'])
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.alter_column('collections', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
