"""add is_important to materials

Revision ID: 5fdecad16de1
Revises: 8f1ade86b5f5
Create Date: 2026-04-18 02:12:40.253452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fdecad16de1'
down_revision: Union[str, Sequence[str], None] = '8f1ade86b5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'materials',
        sa.Column('is_important', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'is_important')
    # ### end Alembic commands ###
