"""add updated_at to materials

Revision ID: d3eff048fd25
Revises: 4fcb8e19c86c
Create Date: 2026-04-19 02:43:03.755837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3eff048fd25'
down_revision: Union[str, Sequence[str], None] = '4fcb8e19c86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'updated_at')
    # ### end Alembic commands ###
