"""updated_all_tables

Revision ID: fa73e1b15eaa
Revises: 2368246d2af2
Create Date: 2026-03-16 11:06:53.390513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa73e1b15eaa'
down_revision: Union[str, Sequence[str], None] = '2368246d2af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('collections_user_id_fkey'), 'collections', type_='foreignkey')
    op.drop_constraint(op.f('collections_parent_id_fkey'), 'collections', type_='foreignkey')
    op.create_foreign_key(None, 'collections', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'collections', 'collections', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('materials_collection_id_fkey'), 'materials', type_='foreignkey')
    op.create_foreign_key(None, 'materials', 'collections', ['collection_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tags_user_id_fkey'), 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key(op.f('tags_user_id_fkey'), 'tags', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key(op.f('materials_collection_id_fkey'), 'materials', 'collections', ['collection_id'], ['id'])
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.create_foreign_key(op.f('collections_parent_id_fkey'), 'collections', 'collections', ['parent_id'], ['id'])
    op.create_foreign_key(op.f('collections_user_id_fkey'), 'collections', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
